on:
  push:
    branches:
      - main
    # paths:
    #   - '/Real_ChatGPT_API/Chapter-3/**'
    # paths-ignore:
    #   - '/Real_ChatGPT_API/Chapter-3/**''

  # workflows_dispatch:
  #   inputs:
  #     username:
  #       description: 
  #       default: 
  #       required:
  #       type: 

###################################################
# 1. action 사용하지 않고 단순 명령어로 빌드 & 배포 자동화 진행
###################################################
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # default:
    #   run: 
    #     shell: bash
    #     working-directory: /Real_ChatGPT_API/Chapter-3/
    steps:
      - name: Build docker image
        run: |
          docker build -f /Real_ChatGPT_API/Chapter-3/Dockerfile -t ${{ secrets.DOCKER_USER }}/chatgpt_assistant_voice:latest . --no-cache
          docker images
      - name: Push docker image on DockerHub
        run: |
          echo ${{ secrets.DOCKER_PW }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          docker push ${{ secrets.DOCKER_USER }}/chatgpt_assistant_voice:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Pull docker image
        run: |
          ssh ubuntu@${{ secrets.SERVER }} 'export DOCKER_HOST="" && docker compose -f ~/bot/docker-compose.yaml up -d'
          ssh ubuntu@${{ secrets.SERVER }} 'docker ps -a'
      
###################################################
# 2. market place의 action 사용하여 빌드 & 배포 자동화 진행
###################################################
# jobs: