on:
  push:
    branches:
      - main
    # paths:
    #   - '/Real_ChatGPT_API/Chapter-3/**'
    # paths-ignore:
    #   - '/Real_ChatGPT_API/Chapter-3/**''

  # workflows_dispatch:
  #   inputs:
  #     username:
  #       description: 
  #       default: 
  #       required:
  #       type: 

###################################################
# 1. action 사용하지 않고 단순 명령어로 빌드 & 배포 자동화 진행
###################################################
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # default:
    #   run: 
    #     shell: bash
    #     working-directory: /Real_ChatGPT_API/Chapter-3/
    steps:
      - name: Build docker image
        run: |
          docker build -f /Real_ChatGPT_API/Chapter-3/Dockerfile -t junius06/chatgpt_assistant_voice:latest . --no-cache
          docker images
      - name: Push docker image on DockerHub
        run: |
          docker login 
          docker push junius06/chatgpt_assistant_voice:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Pull docker image
        run: |
          ssh ubuntu@${{ secret.SERVER }} .. docker pull junius06/chatgpt_assistant_voice:latest
          ssh ubuntu@${{ secret.SERVER }} .. docker ps -a
      
###################################################
# 2. marketplace의 action 사용하여 빌드 & 배포 자동화 진행
###################################################
# jobs: